version: '3.8'

services:
  build-project:
    volumes:
      - type: volume
        source: global
        target: /app
    build:
      dockerfile: Dockerfile

  deploy-project-prod:
    volumes:
      - type: volume
        source: global
        target: /app
    build:
      dockerfile: DockerfileDeploy
    depends_on:
      build-project:
        condition: service_completed_successfully

volumes:
  global: