version: '3.8'

services:
  assembly:
    build:
      dockerfile: Dockerfile
    volumes:
      - 'global:/app'

  prod:
    image: eclipse-temurin:17-jre-alpine
    volumes:
      - 'global:/app'
    expose:
      - 8080
    command: ["java -jar /target/app-0.0.1-SNAPSHOT.jar"]
    depends_on:
      assembly:
        condition: service_completed_successfully

volumes:
  global: