---
# tasks file for common
- name: Ensure python-pip is present
  apt:
    name: python-pip
    state: latest

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Download docker
  pip:
    name:
      - docker
      - requests>=2.20.1
    executable: pip3

- name: Ensure git is present
  apt:
    name: git
    state: present