---
# tasks file for common
- name: Ensure python-pip is present
  apt:
    name: python3-pip
    state: latest

- name: Download docker
  pip:
    name:
      - docker
      - requests>=2.20.1

- name: Ensure git is present
  apt:
    name: git
    state: present