---
# tasks file for aws
- name: Create a new AWS EC2 key pair
  ec2_key:
    name: id_rsa

- name: Create first AWS EC2 instance
  ec2_instance:
    name: "ubuntu-20-4-build-instance"
    image_id: ami-09cd747c78a9add63
    instance_type: t2.micro
    security_group: default
    key_name: "id_rsa"
    vpc_subnet_id: subnet-5ca1ab1e
    volumes:
      ebs:
        volume_type: gp2
        volume_size: 10
    network:
      assign_public_ip: true
  register: firstvm

- name: Create second AWS EC2 instance
  ec2_instance:
    name: "ubuntu-20-4-deploy-instance"
    image_id: ami-09cd747c78a9add63
    instance_type: t2.micro
    security_group: default
    key_name: "id_rsa"
    vpc_subnet_id: subnet-5ca1ab1e
    volumes:
      ebs:
        volume_type: gp2
        volume_size: 10
    network:
      assign_public_ip: true
  register: secondvm

- name: Add host as build
  add_host:
    hostname: "{{ firstvm.instances[0].public_ip_address }}"
    groups: build

- name: Add host as deploy
  add_host:
    hostname: "{{ secondvm.instances[0].public_ip_address }}"
    groups: deploy