---
# tasks file for aws
- name: Create a new AWS EC2 key pair
  ec2_key:
    name: id_rsa
    force: true
  register: ssh_key

- name: Save private key
  copy:
    content: "{{ ssh_key.key.private_key }}"
    dest: ".ssh/id_rsa"
    mode: 0600

- name: Create first AWS EC2 instance
  ec2:
    key_name: id_rsa
    region: us-east-1
    group: default
    instance_type: t2.micro
    image: ami-09cd747c78a9add63
    wait: yes
    count: 1
    vpc_subnet_id: subnet-e96ebeb6
    assign_public_ip: yes
  register: first_vm

- name: Create second AWS EC2 instance
  ec2:
    key_name: id_rsa
    region: us-east-1
    group: default
    instance_type: t2.micro
    image: ami-09cd747c78a9add63
    wait: yes
    count: 1
    vpc_subnet_id: subnet-e96ebeb6
    assign_public_ip: yes
  register: second_vm

- name: Add host as build
  add_host:
    hostname: "{{ first_vm.instances[0].public_ip_address }}"
    groups: build

- name: Add host as deploy
  add_host:
    hostname: "{{ second_vm.instances[0].public_ip_address }}"
    groups: deploy