- name: Provisioning aws configuration
  hosts: localhost
  become: yes

  roles:
    - aws

- name: Provisioning build configuration
  hosts: build
  become: yes

  roles:
    - common
    - build

- name: Provisioning deploy configuration
  hosts: deploy
  become: yes

  roles:
    - common
    - deploy